

import Class.Parq;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author juan esteban
 */
public class Proyecto_Final extends javax.swing.JFrame {

       
    ArrayList<Parq>Lista=new ArrayList<Parq>();
    public Proyecto_Final() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        NomHoraEntrada = new javax.swing.JLabel();
        txtnumplaca = new javax.swing.JTextField();
        NomNumPlaca = new javax.swing.JLabel();
        NomHoraSalida = new javax.swing.JLabel();
        boton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        NomMotoCarro = new javax.swing.JLabel();
        txthoraentrada = new javax.swing.JTextField();
        txthorasalida = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jlbtnSalir = new javax.swing.JLabel();
        jlbtnMin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CupoMotos = new javax.swing.JTextField();
        CupoCarros = new javax.swing.JTextField();
        tipos = new javax.swing.JComboBox<>();
        txtValorHM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtValorHC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtValorFinal = new javax.swing.JTextField();
        btnSalidaCarro = new javax.swing.JButton();
        btnSalidaMoto = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtCupoFinal = new javax.swing.JTextField();
        NomNumPlaca1 = new javax.swing.JLabel();
        txtNombreConductor = new javax.swing.JTextField();
        btnSalidaCarro1 = new javax.swing.JButton();
        txtDatosM = new javax.swing.JTextField();
        txtDatosC = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        Titulo.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Titulo.setText("Control De Parking Digital");

        NomHoraEntrada.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        NomHoraEntrada.setText("Hora De Entrada:");

        txtnumplaca.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        txtnumplaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumplacaActionPerformed(evt);
            }
        });

        NomNumPlaca.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        NomNumPlaca.setText("Número De Placa:");

        NomHoraSalida.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        NomHoraSalida.setText("Hora De Salida:");

        boton.setBackground(new java.awt.Color(0, 153, 153));
        boton.setText("REGISTRAR");
        boton.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });

        tabla.setBackground(new java.awt.Color(0, 153, 153));
        tabla.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "#Placa", "Nombre", "Hora Entrada", "Tipo", "Hora salida"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        NomMotoCarro.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        NomMotoCarro.setText("Tipo de vehiculo:");

        txthoraentrada.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        txthoraentrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthoraentradaActionPerformed(evt);
            }
        });

        txthorasalida.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        txthorasalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthorasalidaActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jlbtnSalir.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jlbtnSalir.setForeground(new java.awt.Color(255, 255, 255));
        jlbtnSalir.setText("X");
        jlbtnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbtnSalirMouseClicked(evt);
            }
        });

        jlbtnMin.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jlbtnMin.setForeground(new java.awt.Color(255, 255, 255));
        jlbtnMin.setText("-");
        jlbtnMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbtnMinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbtnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jlbtnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbtnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Cupo Motos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("Cupo Carros");

        CupoMotos.setEditable(false);
        CupoMotos.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        CupoMotos.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        CupoCarros.setEditable(false);
        CupoCarros.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        CupoCarros.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CupoCarros.setKeymap(null);

        tipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "carro", "moto" }));

        txtValorHM.setEditable(false);
        txtValorHM.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtValorHM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorHMActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Valor Hora Moto");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Valor Hora Carro");

        txtValorHC.setEditable(false);
        txtValorHC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtValorHC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorHCActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("El valor de su tiempo de parqueo es:");

        txtValorFinal.setEditable(false);
        txtValorFinal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btnSalidaCarro.setBackground(new java.awt.Color(0, 153, 153));
        btnSalidaCarro.setText("Salida Carro");
        btnSalidaCarro.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        btnSalidaCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaCarroActionPerformed(evt);
            }
        });

        btnSalidaMoto.setBackground(new java.awt.Color(0, 153, 153));
        btnSalidaMoto.setText("Salida Moto");
        btnSalidaMoto.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        btnSalidaMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaMotoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("%Cupo Completo");

        txtCupoFinal.setEditable(false);
        txtCupoFinal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCupoFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        NomNumPlaca1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        NomNumPlaca1.setText("Nombre Conductor:");

        txtNombreConductor.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        txtNombreConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreConductorActionPerformed(evt);
            }
        });

        btnSalidaCarro1.setBackground(new java.awt.Color(0, 153, 153));
        btnSalidaCarro1.setText("Finanzas");
        btnSalidaCarro1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        btnSalidaCarro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaCarro1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(358, 358, 358))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NomMotoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(tipos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(NomHoraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txthoraentrada, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(boton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NomHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txthorasalida, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NomNumPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NomNumPlaca1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(62, 62, 62)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNombreConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtnumplaca, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(174, 174, 174)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CupoMotos, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtValorHM, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValorHC, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CupoCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtValorFinal)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalidaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalidaMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCupoFinal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalidaCarro1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(Titulo)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NomNumPlaca)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtnumplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CupoCarros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CupoMotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCupoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(NomNumPlaca1)
                    .addComponent(txtNombreConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorHM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorHC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomMotoCarro)
                    .addComponent(tipos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthoraentrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomHoraEntrada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomHoraSalida)
                    .addComponent(txthorasalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalidaMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalidaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalidaCarro1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel1);

        txtDatosM.setEditable(false);
        txtDatosM.setBackground(new java.awt.Color(0, 255, 153));
        getContentPane().add(txtDatosM);

        txtDatosC.setEditable(false);
        txtDatosC.setBackground(new java.awt.Color(0, 255, 153));
        getContentPane().add(txtDatosC);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnumplacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumplacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumplacaActionPerformed

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
   
        Parq Parking = new Parq(txtnumplaca.getText(),txtNombreConductor.getText(),txthoraentrada.getText(),tipos.getSelectedItem().toString(),txthorasalida.getText());
        Lista.add(Parking);
        
        Resultado();
        ValorFinal();
        Restar();
        Actualizar();
        Actualizar2();
        Dinero.txtdinero.setText(txtValorFinal.getText());
        
    }//GEN-LAST:event_botonActionPerformed

    public void Actualizar2(){
    
        int contCcc=Integer.parseInt(CupoCarros.getText());
        int contMmm=Integer.parseInt(CupoMotos.getText());
        
        double CupoCompleto=((contCcc+contMmm)*100)/100;
        
        txtCupoFinal.setText(""+CupoCompleto+"%");
    
    }
    
    public void ValorFinal(){
    int TiempoE=Integer.parseInt(txthoraentrada.getText());
    int TiempoS=Integer.parseInt(txthorasalida.getText());    
    int ValorTiempoMoto=Integer.parseInt(txtValorHM.getText());
    int ValorTiempoCarro=Integer.parseInt(txtValorHC.getText());
    int PrecioM;
    int PrecioC;
    
        String opc = (String)tipos.getSelectedItem();
        
        if (opc.equals("moto")) {
            PrecioM=(TiempoS-TiempoE)*ValorTiempoMoto;
            txtValorFinal.setText(""+PrecioM+"$");

        } else if (opc.equals("carro")) {
            PrecioC=(TiempoS-TiempoE)*ValorTiempoCarro;
            txtValorFinal.setText(""+PrecioC+"$");
        }
    }
    public void Actualizar(){
    
    txthoraentrada.setText("");
    txthorasalida.setText("");
    txtnumplaca.setText("");
    tipos.setSelectedItem("");
    txtNombreConductor.setText("");
    }
    public void Restar(){
        int contC=Integer.parseInt(CupoCarros.getText());
        int contM=Integer.parseInt(CupoMotos.getText());
    String opc = (String)tipos.getSelectedItem();
        
        if (opc.equals("moto")) {
            contM=contM-1;
            CupoMotos.setText(""+contM);
        } else {
            contC=contC-1;
            CupoCarros.setText(""+contC);
        }
        
    }
    public void Resultado(){
    String matris [] []= new String [Lista.size()][5];
    
        for (int i = 0; i < Lista.size(); i++) {
            
           matris [i] [0]= Lista.get(i).getNumPlaca();
           matris [i] [1]= Lista.get(i).getTipo();
           matris [i] [2]= Lista.get(i).getHEntrada();
           matris [i] [3]= Lista.get(i).getHSalida();
           matris [i] [4]= Lista.get(i).getNombre();
            
        }
    tabla.setModel(new javax.swing.table.DefaultTableModel(
            matris,
            new String [] {
                "#Placa", "Nombre", "Hora Entrada", "Tipo", "Hora salida"
            }
        ));
    }
    private void txthoraentradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthoraentradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthoraentradaActionPerformed

    private void txthorasalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthorasalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthorasalidaActionPerformed
       
    private void jlbtnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbtnSalirMouseClicked
        int CerrarC=Integer.parseInt(txtDatosC.getText());
        int CerrarM=Integer.parseInt(txtDatosM.getText());
        int Cerrar=CerrarC+CerrarM;
        int CerrarCc=Integer.parseInt(CupoCarros.getText());
        int CerrarMm=Integer.parseInt(CupoMotos.getText());
        int Cerrar2=CerrarCc+CerrarMm;
        
        if (Cerrar==Cerrar2) {
        System.exit(0);    
        }else{
             
            JOptionPane.showMessageDialog(null,"Todavia existe personas o vehiculos  en el lugar");
        }
        
    }//GEN-LAST:event_jlbtnSalirMouseClicked

    private void jlbtnMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbtnMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jlbtnMinMouseClicked

    private void txtValorHMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorHMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorHMActionPerformed

    private void txtValorHCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorHCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorHCActionPerformed

    private void btnSalidaCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaCarroActionPerformed

        int contC=Integer.parseInt(CupoCarros.getText());
        contC++;
        String numero=String.valueOf(contC);
        CupoCarros.setText(numero);
        Actualizar2();
    }//GEN-LAST:event_btnSalidaCarroActionPerformed

    private void btnSalidaMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaMotoActionPerformed

        
         int contM=Integer.parseInt(CupoMotos.getText());
        contM++;
        String numero=String.valueOf(contM);
        CupoMotos.setText(numero);
        Actualizar2();
        
        
     
    }//GEN-LAST:event_btnSalidaMotoActionPerformed

    private void txtNombreConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreConductorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreConductorActionPerformed

    private void btnSalidaCarro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaCarro1ActionPerformed
        Dinero ProyectoDinero = new Dinero();
        ProyectoDinero.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalidaCarro1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proyecto_Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proyecto_Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proyecto_Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proyecto_Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proyecto_Final().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField CupoCarros;
    public static javax.swing.JTextField CupoMotos;
    private javax.swing.JLabel NomHoraEntrada;
    private javax.swing.JLabel NomHoraSalida;
    private javax.swing.JLabel NomMotoCarro;
    private javax.swing.JLabel NomNumPlaca;
    private javax.swing.JLabel NomNumPlaca1;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton boton;
    private javax.swing.JButton btnSalidaCarro;
    private javax.swing.JButton btnSalidaCarro1;
    private javax.swing.JButton btnSalidaMoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbtnMin;
    private javax.swing.JLabel jlbtnSalir;
    private javax.swing.JTable tabla;
    private javax.swing.JComboBox<String> tipos;
    private javax.swing.JTextField txtCupoFinal;
    public static javax.swing.JTextField txtDatosC;
    public static javax.swing.JTextField txtDatosM;
    private javax.swing.JTextField txtNombreConductor;
    private javax.swing.JTextField txtValorFinal;
    public static javax.swing.JTextField txtValorHC;
    public static javax.swing.JTextField txtValorHM;
    private javax.swing.JTextField txthoraentrada;
    private javax.swing.JTextField txthorasalida;
    private javax.swing.JTextField txtnumplaca;
    // End of variables declaration//GEN-END:variables
}
